config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'projects#index'

  resources :projects do
    resources :categories, except: %i[index] do
      resources :articles, except: %i[index]
    end
  end
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id          :bigint           not null, primary key
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint
#  project_id  :bigint
#  user_id     :bigint
#
# Indexes
#
#  index_articles_on_category_id  (category_id)
#  index_articles_on_project_id   (project_id)
#  index_articles_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (project_id => projects.id)
#  fk_rails_...  (user_id => users.id)
#
class Article < ApplicationRecord
  has_rich_text :content

  # associations
  belongs_to :user
  belongs_to :project
  belongs_to :category

  # validations
  validates :title, presence: true
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  include CategoryScoped

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params.merge(category:, project:, user: current_user))

    article.save
  end

  def update
    article.update(article_params)
  end

  def destroy
    article.destroy!
  end

  private

  def article
    @article ||= category.articles.find(params[:id])
  end
  helper_method :article

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/views/articles/_article.html.erb
<%= link_to project_category_article_path(project, category, article), class: "card mb-3", data: { turbo_frame: :project_content } do %>
  <div class="card-body">
    <%= article.title %>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: [project, category, article], id: 'article_form') do |form| %>
  <%= render "shared/errors", object: article %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :content, class: "form-label" %>
    <%= form.rich_text_area :content, class: "form-control" %>
  </div>

  <div>
    <%= form.submit nil, class: "btn btn-primary" %>
    <%= link_to "Cancel", project_category_path(project, category), class: "btn btn-secondary", data: { "turbo-frame": "project_content" } %>
  </div>
<% end %>

app/views/articles/create.turbo_stream.erb
<% if article.errors.present? %>
  <%= turbo_stream.replace 'article_form', partial: 'form', locals: { article: @article } %>
<% else %>
  <%= turbo_stream.replace :category_content do %>
    <%= turbo_frame_tag :category_content do %>
      <%= render category.articles %>
    <% end %>
  <% end %>
<% end %>

app/views/articles/destroy.turbo_stream.erb
<%= turbo_stream.replace :project_content do %>
  <%= turbo_frame_tag :project_content, src: project_category_path(project, category) %>
<% end %>

app/views/articles/edit.html.erb
<%= turbo_frame_tag :project_content do %>
  <%= render "form", article: article %>
<% end %>

app/views/articles/new.html.erb
<%= turbo_frame_tag :category_content do %>
  <%= render "form", article: article %>
<% end %>

app/views/articles/show.html.erb
<%= turbo_frame_tag :project_content do %>
  <h1><%= article.title %></h1>
  <div class="mb-3"><%= article.content %></div>
  <% if project.owner == current_user %>
    <div class="d-flex">
      <%= link_to edit_project_category_article_path(project, category, article), class: "p-1 btn btn-link", data: { turbo_frame: :project_content } do %>
        <i class="bi bi-pencil-square"></i>
      <% end %>
      <%= button_to project_category_article_path(project, category, article), method: :delete, class: "p-1 btn btn-link", data: { turbo_confirm: t("are_you_sure") } do %>
        <i class="bi bi-trash3"></i>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/articles/update.turbo_stream.erb
<% if article.errors.present? %>
  <%= turbo_stream.replace 'article_form', partial: 'form', locals: { article: article } %>
<% else %>
  <%= turbo_stream.replace :project_content do %>
    <%= turbo_frame_tag :project_content, src: project_category_path(project, category) %>
  <% end %>
<% end %>