config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'projects#index'

  resources :projects do
    resources :categories, except: %i[index] do
      resources :articles, except: %i[index]
    end
  end
end

app/models/project.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: projects
#
#  id          :bigint           not null, primary key
#  description :text
#  is_public   :boolean          default(FALSE)
#  name        :string           default(""), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  owner_id    :bigint
#
# Indexes
#
#  index_projects_on_owner_id  (owner_id)
#
# Foreign Keys
#
#  fk_rails_...  (owner_id => users.id)
#
class Project < ApplicationRecord
  # associations
  belongs_to :owner,
             class_name: 'User',
             foreign_key: 'owner_id'
  has_many :categories, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :project_users
  has_many :users, through: :project_users

  # validations
  validates :name, presence: true

  # scopes
  scope :not_private, -> { where(is_public: true) }
  scope :all_for, lambda { |user|
    where(is_public: true)
      .or(where(owner_id: user.id))
      .or(where(id: user.project_ids))
  }
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :authorize_project, except: %i[index new create]

  def index
    @projects = Project.all_for(current_user)
  end

  def new
    @project = Project.new
  end

  def edit; end

  def create
    @project = Project.new(project_params)
    @project.owner = current_user

    if @project.save
      redirect_to project_url(@project), notice: 'Project was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if project.update(project_params)
      redirect_to project_url(project), notice: 'Project was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    project.destroy

    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  def authorize_project
    return authorize project if params[:id]

    authorize Project
  end

  def project
    @project ||= Project.all_for(current_user).find(params[:id])
  end
  helper_method :project

  def project_params
    params.require(:project).permit(:name, :description, :is_public)
  end
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <%= render "shared/errors", object: project %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.check_box :is_public, class: "form-check-input" %>
    <%= form.label :is_public, "public?", class: "form-check-label" %>
  </div>

  <div>
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= project.is_public %>
  </p>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<div class="row">
  <div class="col-xl-4 col-lg-6">
    <%= render "form", project: project %>
  </div>
</div>

<br>

<div>
  <%= link_to "Show this project", project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<h1>Projects</h1>

<%= link_to "New project", new_project_path, class: "btn btn-primary" %>

<div id="projects" class="mt-3">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Owner</th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= link_to project.name, project %></td>
          <td><%= project.description %></td>
          <td><%= project.owner.nickname %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<div class="row">
  <div class="col-xl-4 col-lg-6">
    <%= render "form", project: @project %>
  </div>
</div>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<div class="d-flex align-items-start">
  <div style="width: 300px" class="p-3 bg-light rounded-3 flex-shrink-0">
    <% if project.owner == current_user %>
      <%= link_to "New category", new_project_category_path(project), class: "w-100 btn btn-primary", data: { "turbo-frame": "project_content" } %>
    <% end %>

    <%= render "shared/categories", project: project %>
  </div>
  <div class="flex-grow-1 mx-3">
    <%= turbo_frame_tag :project_content do %>
      <h1 class="text-center"><%= project.name %></h1>
    <% end %>
  </div>
  <div style="width: 300px" class="p-3 bg-light rounded-3 flex-shrink-0">
    <%= render project %>

    <div class="d-flex justify-content-end">
      <% if policy(project).update? %>
        <%= link_to edit_project_path(project), class: "btn btn-primary me-2" do %>
          Edit
        <% end %>
      <% end %>
      <% if policy(project).destroy? %>
        <%= button_to project, method: :delete, class: "btn btn-danger" do %>
          Destroy
        <% end %>
      <% end %>
    </div>
  </div>
</div>