config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'projects#index'

  resources :projects do
    resources :categories, except: %i[index] do
      resources :articles, except: %i[index]
    end
  end
end

app/models/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  name       :string           default(""), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  parent_id  :bigint
#  project_id :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_categories_on_parent_id   (parent_id)
#  index_categories_on_project_id  (project_id)
#  index_categories_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (parent_id => categories.id)
#  fk_rails_...  (project_id => projects.id)
#  fk_rails_...  (user_id => users.id)
#
class Category < ApplicationRecord
  # associations
  belongs_to :project
  belongs_to :user
  belongs_to :parent,
             class_name: 'Category',
             optional: true
  has_many :children,
           class_name: 'Category',
           foreign_key: :parent_id,
           dependent: :nullify
  has_many :articles, dependent: :nullify

  # validations
  validates :name, presence: true
  validate :cannot_have_itself_as_a_patent
  validate :subcategories_cannot_have_children_categories

  # scopes
  scope :root, -> { where(parent_id: nil) }

  private

  def cannot_have_itself_as_a_patent
    return unless self == parent

    errors.add(:base, :cannot_have_itself_as_a_patent)
  end

  def subcategories_cannot_have_children_categories
    return unless parent&.parent.present? || (parent.present? && children.any?)

    errors.add(:base, :subcategories_cannot_have_children_categories)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  include ProjectScoped

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params.merge(project:, user: current_user))

    category.save
  end

  def update
    category.update(category_params)
  end

  def destroy
    category.destroy!
  end

  private

  def category
    @category ||= Category.find(params[:id])
  end
  helper_method :category

  def category_params
    params.require(:category).permit(:name, :parent_id)
  end
end

app/views/categories/_category.html.erb
<li id="<%= dom_id category %>">
  <div class="d-flex justify-content-between align-items-center border-bottom <%= item_classes if local_assigns[:item_classes] %>">
    <%= link_to category.name, project_category_path(project, category), class: "#{title_classes if local_assigns[:title_classes]}", data: { "turbo-frame": "project_content" } %>
    <% if project.owner == current_user %>
      <div class="d-flex">
        <%= link_to edit_project_category_path(category.project, category), class: "p-1 btn btn-link", data: { turbo_frame: :project_content } do %>
          <i class="bi bi-pencil-square"></i>
        <% end %>
        <%= button_to project_category_path(category.project, category), method: :delete, class: "p-1 btn btn-link", data: { turbo_confirm: t("are_you_sure") } do %>
          <i class="bi bi-trash3"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</li>

app/views/categories/_form.html.erb
<%= form_with(model: [project, category], id: 'category_form') do |form| %>
  <%= render "shared/errors", object: category %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <% if project.categories.root.any? %>
    <div class="mb-3">
      <%= form.label :parent_id, "Parent", class: "form-label" %>
      <%= form.select :parent_id, project.categories.root.pluck(:name, :id), { include_blank: true }, class: "form-control" %>
    </div>
  <% end %>

  <div>
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/create.turbo_stream.erb
<% if @category.errors.present? %>
  <%= turbo_stream.replace 'category_form', partial: 'form', locals: { category: @category } %>
<% else %>
  <%= turbo_stream.replace :project_content do %>
    <%= turbo_frame_tag :project_content %>
  <% end %>

  <%= turbo_stream.replace 'categories', partial: 'shared/categories', locals: { project: project } %>
<% end %>

app/views/categories/destroy.turbo_stream.erb
<%= turbo_stream.remove(category) %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<div class="row">
  <div class="col-xl-4 col-lg-6">
    <%= turbo_frame_tag :project_content do %>
      <%= render "form", category: category %>
    <% end %>
  </div>
</div>

<br>

<%= link_to "Back to project", project_path(project) %>

app/views/categories/new.html.erb
<h1>New category</h1>

<div class="row">
  <div class="col-xl-4 col-lg-6">
    <%= turbo_frame_tag :project_content do %>
      <%= render "form", category: @category %>
    <% end %>
  </div>
</div>

<br>

<%= link_to "Back to project", project_path(project) %>

app/views/categories/show.html.erb
<%= turbo_frame_tag :project_content do %>
  <%= link_to "New article", new_project_category_article_path(project, category), class: "btn btn-primary mb-3", data: { "turbo-frame": "category_content" } %>
  
  <%= turbo_frame_tag :category_content do %>
    <%= render category.articles %>
  <% end %>
<% end %>

app/views/categories/update.turbo_stream.erb
<% if category.errors.present? %>
  <%= turbo_stream.replace 'category_form', partial: 'form', locals: { category: category } %>
<% else %>
  <%= turbo_stream.replace :project_content do %>
    <%= turbo_frame_tag :project_content %>
  <% end %>

  <%= turbo_stream.replace 'categories', partial: 'shared/categories', locals: { project: project } %>
<% end %>